# Generated by Django 5.1.3 on 2026-01-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="product_videos/"),
        ),
    ]
