# Generated by Django 5.1.3 on 2026-01-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_product_category_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(default="My Awesome Shop", max_length=100),
                ),
                (
                    "email",
                    models.EmailField(default="contact@myshop.com", max_length=100),
                ),
                ("country", models.CharField(blank=True, max_length=50)),
                ("city", models.CharField(blank=True, max_length=50)),
                ("district", models.CharField(blank=True, max_length=50)),
                ("street", models.CharField(blank=True, max_length=100)),
                ("detail_address", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
