# Generated by Django 5.1.3 on 2026-01-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
