# Generated by Django 5.1.3 on 2026-02-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="vendor_responded",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
