# Generated by Django 5.1.3 on 2026-02-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_review_rating_reviewmedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="category",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("office", "Office"),
                    ("school", "School"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("N", "Prefer not to say"),
                ],
                default="N",
                max_length=2,
            ),
        ),
    ]
