# Generated by Django 5.1.3 on 2026-02-07 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_shippingaddress_category_user_birth_date_user_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="category",
        ),
        migrations.RemoveField(
            model_name="user",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(default="Unpaid", max_length=20),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("wechat", "WeChat"),
                            ("alipay", "Alipay"),
                            ("mpay", "MPay"),
                            ("credit_card", "Credit Card"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_status", models.CharField(default="Pending", max_length=20)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.order"
                    ),
                ),
            ],
        ),
    ]
