# Generated by Django 5.1.3 on 2026-02-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_shippingaddress_category_user_birth_date_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="vendor_reply",
            field=models.TextField(blank=True, null=True),
        ),
    ]
