
"""
Django settings for myshop project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from core import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
    path("product/<int:product_id>/", views.product_detail, name="product_detail"),  # Added Product Detail Path

    # Cart URLs
    path("cart/add/", views.add_to_cart, name="add_to_cart"),
    path("cart/", views.cart_view, name="cart_view"),
    path("cart/update/", views.update_cart, name="update_cart"),

    # Vendor URLs
    path("vendor/dashboard/", views.vendor_dashboard, name="vendor_dashboard"),
    path("vendor/myshop/", views.vendor_myshop, name="vendor_myshop"),
    path("vendor/products/", views.vendor_products, name="vendor_products"),
    path("vendor/products/add/", views.vendor_add_product, name="vendor_add_product"),
    path("vendor/products/edit/<int:product_id>/", views.vendor_edit_product, name="vendor_edit_product"),
    path("vendor/products/delete/<int:product_id>/", views.vendor_delete_product, name="vendor_delete_product"),
    path("vendor/products/toggle/<int:product_id>/", views.toggle_product_availability, name="toggle_product_availability"),
    path("vendor/products/image/delete/<int:image_id>/", views.delete_product_image, name="delete_product_image"),
    path("vendor/orders/", views.vendor_orders, name="vendor_orders"),

    path('heartbeat/', views.heartbeat, name='heartbeat'),
    path('vendor/product/<int:product_id>/delete-video/', views.delete_product_video, name='delete_product_video'),
]

# Serve media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
